# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/flyin/Desktop/ECE_385/tank1990/tank1990.srcs/sources_1/ip/tank_down_rom_1/tank_down_rom.xci
# IP: The module: 'tank_down_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/flyin/Desktop/ECE_385/tank1990/tank1990.gen/sources_1/ip/tank_down_rom_1/tank_down_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tank_down_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/flyin/Desktop/ECE_385/tank1990/tank1990.srcs/sources_1/ip/tank_down_rom_1/tank_down_rom.xci
# IP: The module: 'tank_down_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/flyin/Desktop/ECE_385/tank1990/tank1990.gen/sources_1/ip/tank_down_rom_1/tank_down_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tank_down_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
