# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7s50csga324-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/bd/mb_block/ipshared/ec67/hdl
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/bd/mb_block/ipshared/7698
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/clk_wiz_0
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/bullet_right_rom_1
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/bullet_left_rom_1
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/bullet_down_rom_1
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/bullet_up_rom_1
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/bd/mb_block/ip/mb_block_axi_quad_spi_0_0/netlist
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/tank_left_rom_2
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/tank_right_rom
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/tank_up_rom_1
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/tank_down_rom_1
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/base_rom
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/brick_rom_1
  } {
      C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -sv -include {
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/bd/mb_block/ipshared/ec67/hdl
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/bd/mb_block/ipshared/7698
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/clk_wiz_0
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/bullet_right_rom_1
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/bullet_left_rom_1
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/bullet_down_rom_1
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/bullet_up_rom_1
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/bd/mb_block/ip/mb_block_axi_quad_spi_0_0/netlist
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/tank_left_rom_2
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/tank_right_rom
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/tank_up_rom_1
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/tank_down_rom_1
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/base_rom
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/brick_rom_1
  } {
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.srcs/sources_1/imports/design_source/VGA_controller.sv
      C:/Users/Leo/Documents/GitHub/tank1990/sprites/base/base.sv
      C:/Users/Leo/Documents/GitHub/tank1990/sprites/base/base_palette.sv
      C:/Users/Leo/Documents/GitHub/tank1990/sprites/bricks/brick_map1.sv
      C:/Users/Leo/Documents/GitHub/tank1990/sprites/bricks/brick_palette.sv
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.srcs/sources_1/imports/drive-download-20250428T170917Z-001/bullet_down.sv
      C:/Users/Leo/Documents/GitHub/tank1990/sprites/bullet_down/bullet_down_palette.sv
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.srcs/sources_1/imports/drive-download-20250428T170917Z-001/bullet_left.sv
      C:/Users/Leo/Documents/GitHub/tank1990/sprites/bullet_left/bullet_left_palette.sv
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.srcs/sources_1/imports/drive-download-20250428T170917Z-001/bullet_right.sv
      C:/Users/Leo/Documents/GitHub/tank1990/sprites/bullet_right/bullet_right_palette.sv
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.srcs/sources_1/imports/drive-download-20250428T170917Z-001/bullet_up.sv
      C:/Users/Leo/Documents/GitHub/tank1990/sprites/bullet_up/bullet_up_palette.sv
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.srcs/sources_1/new/color_picker.sv
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.srcs/sources_1/new/enemy_ai_controller.sv
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.srcs/sources_1/new/enemy_tank_down_palette.sv
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.srcs/sources_1/new/enemy_tank_left_palette.sv
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.srcs/sources_1/new/enemy_tank_right_palette.sv
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.srcs/sources_1/new/enemy_tank_up_palette.sv
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.srcs/sources_1/imports/design_source/hex_driver.sv
      C:/Users/Leo/Documents/GitHub/tank1990/level_1_map.sv
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.srcs/sources_1/new/player_controller.sv
      C:/Users/Leo/Documents/GitHub/tank1990/sprites/tank.sv
      C:/Users/Leo/Documents/GitHub/tank1990/sprites/tank_down/tank_down.sv
      C:/Users/Leo/Documents/GitHub/tank1990/sprites/tank_down/tank_down_palette.sv
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.srcs/sources_1/new/tank_explosion_multi.sv
      C:/Users/Leo/Documents/GitHub/tank1990/sprites/tank_left/tank_left.sv
      C:/Users/Leo/Documents/GitHub/tank1990/sprites/tank_left/tank_left_palette.sv
      C:/Users/Leo/Documents/GitHub/tank1990/sprites/tank_right/tank_right.sv
      C:/Users/Leo/Documents/GitHub/tank1990/sprites/tank_right/tank_right_palette.sv
      C:/Users/Leo/Documents/GitHub/tank1990/sprites/tank_top_level.sv
      C:/Users/Leo/Documents/GitHub/tank1990/sprites/tank_up/tank_up.sv
      C:/Users/Leo/Documents/GitHub/tank1990/sprites/tank_up/tank_up_palette.sv
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.srcs/sources_1/imports/design_source/mb_usb_hdmi_top.sv
    }
      rt::read_verilog -include {
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/bd/mb_block/ipshared/ec67/hdl
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/bd/mb_block/ipshared/7698
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/clk_wiz_0
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/bullet_right_rom_1
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/bullet_left_rom_1
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/bullet_down_rom_1
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/bullet_up_rom_1
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/bd/mb_block/ip/mb_block_axi_quad_spi_0_0/netlist
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/tank_left_rom_2
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/tank_right_rom
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/tank_up_rom_1
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/tank_down_rom_1
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/base_rom
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/brick_rom_1
  } {
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/bullet_right_rom_stub.v
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/bullet_left_rom_stub.v
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/bullet_down_rom_stub.v
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/bullet_up_rom_stub.v
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/mb_block_microblaze_0_0_stub.v
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/mb_block_dlmb_v10_0_stub.v
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/mb_block_ilmb_v10_0_stub.v
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/mb_block_dlmb_bram_if_cntlr_0_stub.v
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/mb_block_ilmb_bram_if_cntlr_0_stub.v
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/mb_block_lmb_bram_0_stub.v
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/mb_block_xbar_0_stub.v
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/mb_block_microblaze_0_axi_intc_0_stub.v
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/mb_block_mdm_1_0_stub.v
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/mb_block_clk_wiz_1_0_stub.v
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/mb_block_rst_clk_wiz_1_100M_0_stub.v
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/mb_block_axi_quad_spi_0_0_stub.v
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/mb_block_axi_uartlite_0_0_stub.v
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/mb_block_axi_timer_0_0_stub.v
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/mb_block_axi_gpio_0_0_stub.v
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/mb_block_axi_gpio_0_1_stub.v
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/mb_block_axi_gpio_0_2_stub.v
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/hdmi_tx_0_stub.v
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/clk_wiz_0_stub.v
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/tank_left_rom_stub.v
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/tank_right_rom_stub.v
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/tank_up_rom_stub.v
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/tank_down_rom_stub.v
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/base_rom_stub.v
      C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/brick_rom_stub.v
      c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/bd/mb_block/synth/mb_block.v
    }
      rt::read_verilog -include {
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/bd/mb_block/ipshared/ec67/hdl
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/bd/mb_block/ipshared/7698
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/clk_wiz_0
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/bullet_right_rom_1
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/bullet_left_rom_1
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/bullet_down_rom_1
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/bullet_up_rom_1
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/bd/mb_block/ip/mb_block_axi_quad_spi_0_0/netlist
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/tank_left_rom_2
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/tank_right_rom
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/tank_up_rom_1
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/tank_down_rom_1
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/base_rom
    c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/ip/brick_rom_1
  } {
      c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/bd/mb_block/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v
      c:/Users/Leo/Documents/GitHub/tank1990/tank1990.gen/sources_1/bd/mb_block/ip/mb_block_microblaze_0_xlconcat_0/synth/mb_block_microblaze_0_xlconcat_0.v
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/realtime/mb_usb_hdmi_top_synth.xdc
    rt::sdcChecksum
    set rt::top mb_usb_hdmi_top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {C:/Users/Leo/Documents/GitHub/tank1990/tank1990.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/Leo/Documents/GitHub/tank1990/tank1990.runs/synth_1/.Xil/Vivado-5560-Leo/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    rt::close_pss_mem_watcher
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    rt::set_parameter incrementalOnCache ""
    rt::set_parameter doIncremental false
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
